# æœºåœºè®¢é˜…
proxy-providers:
  zsh:
    url: "https://zhs.futbol/link/whYbmVLDYRUzadUW?is_ss=5&dns=1&tj=1&disney&y2b&ai&nf"
    type: http
    interval: 86400
    path: ./providers/zhs.tw.yaml
    proxy: DIRECT
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      lazy: true
      expected-status: 204
    
# å…¨å±€é…ç½® 
mode: rule
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: info
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true
geodata-mode: false
# memconservative/standard
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  metadb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
  asn: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"

# å…¥ç«™  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "GEOSITE:private"
    - "GEOSITE:cn"
  default-nameserver:
    - 119.29.29.29
  proxy-server-nameserver:
    - 211.136.192.6
    - 120.196.165.24
    - 119.29.29.29
  nameserver:
    - 211.136.192.6
    - 120.196.165.24
    - 119.29.29.29
 
# å‡ºç«™ç­–ç•¥
pr: &pr {type: select, proxies: [é»˜è®¤ä»£ç†, ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, æ¨èèŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ èŠ‚ç‚¹, ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹, ä¹°æ¸¸æˆèŠ‚ç‚¹, DIRECT]}
proxy-groups:
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, type: url-test, timeout: 5000, tolerance: 50, interval: 300, max-failed-times: 3, expected-status: 204, filter: "(?i)TW", use: [zsh]}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, type: url-test, timeout: 5000, tolerance: 50, interval: 300, max-failed-times: 3, expected-status: 204, filter: "(?i)HK", use: [zsh]}
  - {name: é»˜è®¤ä»£ç†, type: select, proxies: [ æ¨èèŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªåŠ¨, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ æ–°åŠ èŠ‚ç‚¹, DIRECT], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png}
  - {name: æ¨èèŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)è", use: [zsh], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png}
  - {name: æ¼ç½‘ä¹‹é±¼, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, type: url-test, timeout: 5000, tolerance: 50, interval: 300, max-failed-times: 3, expected-status: 204, filter: "(?i)US", use: [zsh]}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, type: url-test, timeout: 5000, tolerance: 50, interval: 300, max-failed-times: 3, expected-status: 204, filter: "(?i)JP", use: [zsh]}
  - {name: YouTube, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png}
  - {name: ChatGPT, <<: *pr, icon: https://fastly.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/openai.png}
  - {name: TikTok, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png}
  - {name: Apple, type: select, proxies: [DIRECT,  é»˜è®¤ä»£ç†], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png}
  - {name: GitHub, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png}
  - {name: Google, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png}
  - {name: Telegram, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png}
  - {name: NETFLIX, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png}
  - {name: Speedtest, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png}
  - {name: PayPal, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/PayPal.png}
  - {name: å…¨éƒ¨èŠ‚ç‚¹, type: select, use: [zsh], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png}
  - {name: ä¹°æ¸¸æˆèŠ‚ç‚¹, type: select, filter: "(?i)RU|BR|TR", use: [zsh], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ èŠ‚ç‚¹, type: select, filter: "(?i)SG", use: [zsh]}
  - {name: ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹, type: select, filter: "(?i)UK", use: [zsh]}


# è§„åˆ™åŒ¹é…
rules:
  # GEOSITE è§„åˆ™
  - GEOSITE,private, DIRECT
  - GEOSITE,category-scholar-!cn, é»˜è®¤ä»£ç†
  - GEOSITE,biliintl, é»˜è®¤ä»£ç†
  - GEOSITE,steam@cn, DIRECT
  - GEOSITE,category-games@cn, DIRECT
  - GEOSITE,pixiv, é»˜è®¤ä»£ç†
  - GEOSITE,apple-cn, DIRECT
  - GEOSITE,apple, Apple
  - GEOSITE,category-ai-!cn, ChatGPT
  - GEOSITE,github, GitHub
  - GEOSITE,youtube, YouTube
  - GEOSITE,google, Google
  - GEOSITE,twitter, é»˜è®¤ä»£ç†
  - GEOSITE,microsoft@cn, DIRECT
  - GEOSITE,onedrive, DIRECT
  - GEOSITE,tiktok, TikTok
  - GEOSITE,speedtest, Speedtest
  - GEOSITE,telegram, Telegram
  - GEOSITE,netflix, NETFLIX
  - GEOSITE,paypal, PayPal
  - GEOSITE,gfw, é»˜è®¤ä»£ç†
  - GEOSITE,geolocation-!cn, é»˜è®¤ä»£ç†
  - GEOSITE,cn, DIRECT

  # GEOIP è§„åˆ™
  - GEOIP,private, DIRECT,no-resolve
  - GEOIP,google, Google,no-resolve
  - GEOIP,netflix, NETFLIX,no-resolve
  - GEOIP,telegram, Telegram,no-resolve
  - GEOIP,cn, DIRECT
  # - DST-PORT,80/8080/443/8443,é»˜è®¤ä»£ç†
  - MATCH, æ¼ç½‘ä¹‹é±¼
