# 基础环境配置
env:
  log_level: "INFO"
  debug: false
  mode: 1

# 远程环境配置
remote:
  user: "nvidia"
  ip: "192.168.10.2"
  data_root: "/mdrive_data/bag"

# 宿主机路径管理
host:
  nas_root: "/media/nas/00.raw"
  dest_root: "/media/road_test"
  mdrive_root: "/home/mini/project"
  vmc_sh_path: "/home/mini/project/vmc.sh"
  local_path: "/media/mini"

# Docker 内部路径管理
docker:
  # image: "gcr.minieye.tech/ad/package/mdrive"
  container: "mdrive_dev_vmc_minieye"
  workspace: "/mdrive"
  host_mount: "/media"
  docker_mount: "/media"
  dev_into: "/home/mini/project/mdrive/docker/dev_into.sh"
  dev_start: "/home/mini/project/mdrive/docker/dev_start.sh"
  setup_env: "/mdrive/mdrive/setup.sh"


# 业务逻辑配置
logic:
  vehicle: "XZB600011" # 临时测试
  target_date: "20260110" # 临时测试
  version_json: ""
  soc: "soc1"
  before: 30
  after: 10
  blacklist:

paths:
  scripts_dir: "./scripts"
