# 基础环境配置
env:
  log_level: "INFO"
  debug: False
  mode: 1

# 远程环境配置
remote:
  user: "nvidia"
  ip: "192.168.10.2"
  data_root: "/mdrive_data/bag"

# 宿主机路径管理
host:
  nas_root: "/media/nas/00.raw"
  dest_root: "/media/road_test"
  mdrive_root: "/home/mini/project"
  local_path: "/media/mini"
  # local_path: "/media/data" # 测试


# Docker 内部路径管理
docker:
  container: "mdrive_dev_vmc_minieye"
  workspace: "/mdrive"
  host_mount: "/media"
  docker_mount: "/media"
  docker_scripts: "/home/mini/project/mdrive/docker"
  setup_env: "/mdrive/mdrive/setup.sh"

# 业务逻辑配置
logic:
  vehicle: "XZB600011" # 临时测试
  target_date: "20251227" # 临时测试
  mode: 1
  version_json: ""
  soc: "soc1"
  before: 15
  after: 0
  blacklist:

paths:
  scripts_dir: "./scripts"
