# 远程环境配置
remote:
  user: "nvidia"
  ip: "192.168.10.2"
  data_root: "/mdrive_data/bag"

# 宿主机路径管理
host:
  nas_root: "/media/nas/00.raw"
  dest_root: "/media/road_test"
  mdrive_root: "/home/mini/project"
  data_root: "/media/mini/data"

# Docker 内部路径管理
docker:
  container: "mdrive_dev_vmc_minieye"
  workspace: "/mdrive"
  host_mount: "/media"
  docker_mount: "/media"
  docker_scripts: "/home/mini/project/mdrive/docker"
  setup_env: "/mdrive/mdrive/setup.sh"

# 业务逻辑配置
logic:
  vehicle: "XZB600013" # 临时测试
  target_date: "20260101"
  # mode: 1
  version: ""
  soc: "soc"
  before: 15
  after: 0
  blacklist:

paths:
  scripts_dir: "./scripts"
